package neu.edu;
// Generated Nov 3, 2016 6:47:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userName;
	private String name;
	private String password;
	private String dob;
	private String gender;
	private String linesaboutyou;
	private String emailaddress;
	private String phonenumber;
	private String address;
	private String project1name;
	private String project2name;
	private String rateSkill3;
	private String project1description;
	private String project2description;
	private String university;
	private String relevantCourses;
	private String company;
	private String position;
	private String jobDescription;
	private String skill1;
	private String rateSkill1;
	private String skill2;
	private String rateSkill2;
	private String skill3;
	private String reference1name;
	private String reference1email;
	private String reference1relation;
	private String reference2name;
	private String reference2email;
	private String userscol;

	public Users() {
	}

	public Users(String userName) {
		this.userName = userName;
	}

	public Users(String userName, String name, String password, String dob, String gender, String linesaboutyou,
			String emailaddress, String phonenumber, String address, String project1name, String project2name,
			String rateSkill3, String project1description, String project2description, String university,
			String relevantCourses, String company, String position, String jobDescription, String skill1,
			String rateSkill1, String skill2, String rateSkill2, String skill3, String reference1name,
			String reference1email, String reference1relation, String reference2name, String reference2email,
			String userscol) {
		this.userName = userName;
		this.name = name;
		this.password = password;
		this.dob = dob;
		this.gender = gender;
		this.linesaboutyou = linesaboutyou;
		this.emailaddress = emailaddress;
		this.phonenumber = phonenumber;
		this.address = address;
		this.project1name = project1name;
		this.project2name = project2name;
		this.rateSkill3 = rateSkill3;
		this.project1description = project1description;
		this.project2description = project2description;
		this.university = university;
		this.relevantCourses = relevantCourses;
		this.company = company;
		this.position = position;
		this.jobDescription = jobDescription;
		this.skill1 = skill1;
		this.rateSkill1 = rateSkill1;
		this.skill2 = skill2;
		this.rateSkill2 = rateSkill2;
		this.skill3 = skill3;
		this.reference1name = reference1name;
		this.reference1email = reference1email;
		this.reference1relation = reference1relation;
		this.reference2name = reference2name;
		this.reference2email = reference2email;
		this.userscol = userscol;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getLinesaboutyou() {
		return this.linesaboutyou;
	}

	public void setLinesaboutyou(String linesaboutyou) {
		this.linesaboutyou = linesaboutyou;
	}

	public String getEmailaddress() {
		return this.emailaddress;
	}

	public void setEmailaddress(String emailaddress) {
		this.emailaddress = emailaddress;
	}

	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getProject1name() {
		return this.project1name;
	}

	public void setProject1name(String project1name) {
		this.project1name = project1name;
	}

	public String getProject2name() {
		return this.project2name;
	}

	public void setProject2name(String project2name) {
		this.project2name = project2name;
	}

	public String getRateSkill3() {
		return this.rateSkill3;
	}

	public void setRateSkill3(String rateSkill3) {
		this.rateSkill3 = rateSkill3;
	}

	public String getProject1description() {
		return this.project1description;
	}

	public void setProject1description(String project1description) {
		this.project1description = project1description;
	}

	public String getProject2description() {
		return this.project2description;
	}

	public void setProject2description(String project2description) {
		this.project2description = project2description;
	}

	public String getUniversity() {
		return this.university;
	}

	public void setUniversity(String university) {
		this.university = university;
	}

	public String getRelevantCourses() {
		return this.relevantCourses;
	}

	public void setRelevantCourses(String relevantCourses) {
		this.relevantCourses = relevantCourses;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getJobDescription() {
		return this.jobDescription;
	}

	public void setJobDescription(String jobDescription) {
		this.jobDescription = jobDescription;
	}

	public String getSkill1() {
		return this.skill1;
	}

	public void setSkill1(String skill1) {
		this.skill1 = skill1;
	}

	public String getRateSkill1() {
		return this.rateSkill1;
	}

	public void setRateSkill1(String rateSkill1) {
		this.rateSkill1 = rateSkill1;
	}

	public String getSkill2() {
		return this.skill2;
	}

	public void setSkill2(String skill2) {
		this.skill2 = skill2;
	}

	public String getRateSkill2() {
		return this.rateSkill2;
	}

	public void setRateSkill2(String rateSkill2) {
		this.rateSkill2 = rateSkill2;
	}

	public String getSkill3() {
		return this.skill3;
	}

	public void setSkill3(String skill3) {
		this.skill3 = skill3;
	}

	public String getReference1name() {
		return this.reference1name;
	}

	public void setReference1name(String reference1name) {
		this.reference1name = reference1name;
	}

	public String getReference1email() {
		return this.reference1email;
	}

	public void setReference1email(String reference1email) {
		this.reference1email = reference1email;
	}

	public String getReference1relation() {
		return this.reference1relation;
	}

	public void setReference1relation(String reference1relation) {
		this.reference1relation = reference1relation;
	}

	public String getReference2name() {
		return this.reference2name;
	}

	public void setReference2name(String reference2name) {
		this.reference2name = reference2name;
	}

	public String getReference2email() {
		return this.reference2email;
	}

	public void setReference2email(String reference2email) {
		this.reference2email = reference2email;
	}

	public String getUserscol() {
		return this.userscol;
	}

	public void setUserscol(String userscol) {
		this.userscol = userscol;
	}

}
